package generator

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"wiresmith/compiler/types"

	"github.com/bufbuild/protocompile"
	"github.com/bufbuild/protocompile/reporter"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

type Generator struct {
	Module        string
	OutDir        string
	ProtoDir      string
	StripPrefix   string // proto package prefix to strip for Go paths
	ImportBase    string // replaces module+"/gen/" in import paths
	HelpersImport string // replaces module+"/gen/protohelpers"

	goPackages map[string]string // built during Generate, proto pkg -> go_package value
}

type FileGenerator struct {
	fd      protoreflect.FileDescriptor
	imports *ImportTracker
	body    *bytes.Buffer
}

// Emitter interface implementation for FileGenerator.

func (fg *FileGenerator) Writef(format string, args ...any) {
	fmt.Fprintf(fg.body, format, args...)
}

func (fg *FileGenerator) ReverseTag(indent string, num protowire.Number, wt protowire.Type) {
	fg.reverseTag(indent, num, wt)
}

func (fg *FileGenerator) AddImport(path, alias string) {
	fg.imports.addImport(path, alias)
}

// fieldContext builds a FieldContext from a field descriptor.
func (fg *FileGenerator) fieldContext(fd protoreflect.FieldDescriptor) types.FieldContext {
	ctx := types.FieldContext{}
	if fd.Kind() == protoreflect.EnumKind {
		ctx.EnumType = fg.imports.goEnumType(fd.Enum())
	}
	if fd.Kind() == protoreflect.MessageKind {
		ctx.MessageType = fg.imports.goSingularType(fd)
		msgPkg := string(fd.Message().ParentFile().Package())
		ctx.IsSamePackage = (msgPkg == fg.imports.selfPkg)
	}
	return ctx
}

func (g *Generator) Generate(ctx context.Context) error {
	mapping, importPaths, err := buildImportMapping(g.ProtoDir)
	if err != nil {
		return fmt.Errorf("building import mapping: %w", err)
	}

	resolver := &memResolver{files: mapping}
	compiler := protocompile.Compiler{
		Resolver:       resolver,
		SourceInfoMode: protocompile.SourceInfoStandard,
		Reporter: reporter.NewReporter(
			func(err reporter.ErrorWithPos) error { return err },
			nil,
		),
	}

	results, err := compiler.Compile(ctx, importPaths...)
	if err != nil {
		return fmt.Errorf("compiling protos: %w", err)
	}

	g.goPackages = make(map[string]string)
	for _, fd := range results {
		opts, _ := fd.Options().(*descriptorpb.FileOptions)
		if opts != nil {
			if goPkg := opts.GetGoPackage(); goPkg != "" {
				g.goPackages[string(fd.Package())] = goPkg
			}
		}
	}

	for _, fd := range results {
		if err := g.generateFile(fd); err != nil {
			return fmt.Errorf("generating %s: %w", fd.Path(), err)
		}
	}
	return nil
}

func (g *Generator) generateFile(fd protoreflect.FileDescriptor) error {
	fg := &FileGenerator{
		fd:      fd,
		imports: newImportTracker(g.Module, string(fd.Package()), g.StripPrefix, g.ImportBase, g.HelpersImport, g.goPackages),
		body:    &bytes.Buffer{},
	}

	fg.emitAllEnums(fd)
	fg.emitAllOneofs(fd)
	fg.emitAllStructs(fd)
	fg.emitAllResetMethods(fd)
	fg.emitAllHasMethods(fd)
	fg.emitAllGetterMethods(fd)
	fg.emitAllSizeMethods(fd)
	fg.emitAllMarshalMethods(fd)
	fg.emitAllUnmarshalMethods(fd)
	fg.emitAllEqualMethods(fd)
	fg.emitRegistration(fd)

	var out bytes.Buffer
	fg.emitHeader(&out)
	out.Write(fg.body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		// Write unformatted for debugging
		formatted = out.Bytes()
		fmt.Fprintf(os.Stderr, "warning: format error for %s: %v\n", fd.Path(), err)
	}

	pkg := string(fd.Package())
	dir := filepath.Join(g.OutDir, g.resolveDir(pkg))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	// Use the proto filename without extension as the Go filename
	base := filepath.Base(fd.Path())
	base = strings.TrimSuffix(base, ".proto") + ".pb.go"
	outPath := filepath.Join(dir, base)

	return os.WriteFile(outPath, formatted, 0o644)
}

func (fg *FileGenerator) emitHeader(out *bytes.Buffer) {
	pkg := string(fg.fd.Package())
	fmt.Fprintf(out, "// Code generated by wiresmith. DO NOT EDIT.\n")
	fmt.Fprintf(out, "// source: %s\n\n", fg.fd.Path())
	fmt.Fprintf(out, "package %s\n\n", fg.imports.resolvePkgName(pkg))

	// Collect all imports
	type imp struct {
		path  string
		alias string
	}
	var imps []imp
	for path, alias := range fg.imports.imports {
		imps = append(imps, imp{path, alias})
	}
	sort.Slice(imps, func(i, j int) bool { return imps[i].path < imps[j].path })

	if len(imps) > 0 {
		fmt.Fprintf(out, "import (\n")
		for _, i := range imps {
			if i.alias != "" && !strings.HasSuffix(i.path, "/"+i.alias) {
				fmt.Fprintf(out, "\t%s %q\n", i.alias, i.path)
			} else {
				fmt.Fprintf(out, "\t%q\n", i.path)
			}
		}
		fmt.Fprintf(out, ")\n\n")
	}
}

func (fg *FileGenerator) emitAllEnums(fd protoreflect.FileDescriptor) {
	for i := 0; i < fd.Enums().Len(); i++ {
		fg.emitEnum(fd.Enums().Get(i))
	}
	forEachMessage(fd, func(md protoreflect.MessageDescriptor) {
		for i := 0; i < md.Enums().Len(); i++ {
			fg.emitEnum(md.Enums().Get(i))
		}
	})
}

func (fg *FileGenerator) emitAllOneofs(fd protoreflect.FileDescriptor) {
	forEachMessage(fd, func(md protoreflect.MessageDescriptor) {
		for i := 0; i < md.Oneofs().Len(); i++ {
			oo := md.Oneofs().Get(i)
			if oo.IsSynthetic() {
				continue
			}
			fg.emitOneof(md, oo)
		}
	})
}

func (fg *FileGenerator) emitAllStructs(fd protoreflect.FileDescriptor) {
	forEachMessage(fd, fg.emitStruct)
}

func (fg *FileGenerator) emitAllHasMethods(fd protoreflect.FileDescriptor) {
	forEachMessage(fd, fg.emitHasMethods)
}

func (fg *FileGenerator) emitAllSizeMethods(fd protoreflect.FileDescriptor) {
	forEachMessage(fd, fg.emitSize)
}

func (fg *FileGenerator) emitAllMarshalMethods(fd protoreflect.FileDescriptor) {
	forEachMessage(fd, fg.emitMarshal)
}

func (fg *FileGenerator) emitAllUnmarshalMethods(fd protoreflect.FileDescriptor) {
	// Emit the max recursion depth constant and skip helpers once per file.
	fmt.Fprintf(fg.body, "const maxUnmarshalDepth = 10000\n\n")
	fg.emitSkipValueHelper()
	forEachMessage(fd, fg.emitUnmarshal)
}

// forEachMessage calls fn for every message reachable from fd, skipping
// nested map-entry messages and visiting nested messages before their
// parent (post-order).
func forEachMessage(fd protoreflect.FileDescriptor, fn func(protoreflect.MessageDescriptor)) {
	for i := 0; i < fd.Messages().Len(); i++ {
		walkMessages(fd.Messages().Get(i), fn)
	}
}

func walkMessages(md protoreflect.MessageDescriptor, fn func(protoreflect.MessageDescriptor)) {
	for i := 0; i < md.Messages().Len(); i++ {
		nested := md.Messages().Get(i)
		if nested.IsMapEntry() {
			continue
		}
		walkMessages(nested, fn)
	}
	fn(md)
}

// isRealOneof returns true if the field belongs to a non-synthetic oneof.
func isRealOneof(fd protoreflect.FieldDescriptor) bool {
	oo := fd.ContainingOneof()
	return oo != nil && !oo.IsSynthetic()
}

// oneofInterfaceName returns the Go interface name for a oneof.
func oneofInterfaceName(md protoreflect.MessageDescriptor, oo protoreflect.OneofDescriptor) string {
	return goMessageTypeName(md) + "_" + snakeToPascal(string(oo.Name()))
}

// oneofVariantName returns the Go struct name for a oneof variant.
func oneofVariantName(md protoreflect.MessageDescriptor, fd protoreflect.FieldDescriptor) string {
	return goMessageTypeName(md) + "_" + snakeToPascal(string(fd.Name()))
}

// buildImportMapping reads proto files (recursively) and builds a mapping from
// import paths to file contents. For nested files the import key is the
// relative filesystem path; for top-level files it is the package-derived path
// (backwards compatible with flat proto directories).
func buildImportMapping(protoDir string) (map[string][]byte, []string, error) {
	mapping := make(map[string][]byte)
	var importPaths []string
	pkgRE := regexp.MustCompile(`(?m)^package\s+([\w.]+)\s*;`)

	err := filepath.WalkDir(protoDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".proto") {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		m := pkgRE.FindSubmatch(content)
		if m == nil {
			return fmt.Errorf("no package found in %s", path)
		}

		rel, err := filepath.Rel(protoDir, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)

		if strings.Contains(rel, "/") {
			// Nested file: use relative path as import key.
			if _, exists := mapping[rel]; exists {
				return fmt.Errorf("duplicate import key %q (from %s)", rel, path)
			}
			mapping[rel] = content
			importPaths = append(importPaths, rel)
		} else {
			// Top-level file: compile under the package-derived path
			// (backwards compat), but also register the plain filename
			// in the resolver so nested protos can import by relative path.
			pkg := string(m[1])
			pkgKey := strings.ReplaceAll(pkg, ".", "/") + "/" + d.Name()
			if _, exists := mapping[pkgKey]; exists {
				return fmt.Errorf("duplicate import key %q (from %s)", pkgKey, path)
			}
			mapping[pkgKey] = content
			importPaths = append(importPaths, pkgKey)
			// Also register the plain filename for resolver lookups.
			if rel != pkgKey {
				mapping[rel] = content
			}
		}
		return nil
	})
	if err != nil {
		return nil, nil, err
	}

	sort.Strings(importPaths)
	return mapping, importPaths, nil
}

func (g *Generator) resolveDir(protoPkg string) string {
	if _, relDir, _, ok := resolveGoPackage(protoPkg, g.goPackages, effectiveBase(g.Module, g.ImportBase)); ok {
		return relDir
	}
	return goPackageDir(protoPkg, g.StripPrefix)
}

// memResolver serves proto file content from memory.
type memResolver struct {
	files map[string][]byte
}

func (r *memResolver) FindFileByPath(path string) (protocompile.SearchResult, error) {
	content, ok := r.files[path]
	if !ok {
		return protocompile.SearchResult{}, os.ErrNotExist
	}
	return protocompile.SearchResult{
		Source: bytes.NewReader(content),
	}, nil
}
