// SPDX-License-Identifier: Apache-2.0
//
// The vendored grpc.go references three package-level identifiers that
// protoc-gen-go-grpc upstream declares in its own main.go (which wiresmith
// does not vendor — wiresmith ships no stand-alone protoc plugin binary
// for the gRPC stub generator). Reproduce them here so grpc.go can stay
// byte-identical to upstream and future re-syncs are a straight `cp`:
//
//	var requireUnimplemented *bool   // wired upstream to a flag.Bool default true
//	var useGenericStreams    *bool   // wired upstream to a flag.Bool default true
//	const version            string  // upstream main.go: const version = "1.6.0"
//
// We pin the booleans to upstream's defaults (both true). `version` carries
// the vendored upstream tag verbatim so the generated "Code generated by
// protoc-gen-go-grpc" banner reports the source-of-truth version we
// vendored — bump it in lockstep when re-syncing grpc.go from upstream.
package grpc

const version = "1.6.0"

var (
	defaultTrue          = true
	requireUnimplemented = &defaultTrue
	useGenericStreams    = &defaultTrue
)
