// Code generated by wiresmith. DO NOT EDIT.
// source: types/known/anypb/any.proto

package anypb

import (
	"strconv"
	"strings"
)

// Per-message String() methods for types/known/anypb/any.proto.
//
// String() is a hand-rolled, deterministic debug dump: pointer fields are
// dereferenced to their value (so optional scalars, oneof payloads,
// pointer-option, and recursive fields render content, never a heap
// address), nested messages recurse through their own String(), and map
// keys are sorted — so the output is content- and byte-deterministic.
// It does NOT use protoimpl.X.MessageStringOf / prototext: those walk
// fields via google.golang.org/protobuf reflection, which wiresmith's
// ProtoReflect bridge panics on (value-typed message fields are
// incompatible with the official field converters).
//
// Why a separate file? String() is never called from Marshal/Unmarshal/
// Size; emitting it next to those hot methods costs icache/iTLB locality
// for no benefit — same split rationale as _reflect / _compare / _equal.
// See compiler/generator/emit_string.go. DO NOT inline back into the main
// .pb.go without re-measuring.

func (m *Any) String() string {
	if m == nil {
		return "<nil>"
	}
	var b strings.Builder
	if len(m.TypeUrl) > 0 {
		b.WriteString("type_url: ")
		b.WriteString(strconv.Quote(m.TypeUrl))
		b.WriteString(" ")
	}
	if len(m.Value) > 0 {
		b.WriteString("value: ")
		b.WriteString(strconv.Quote(string(m.Value)))
		b.WriteString(" ")
	}
	return strings.TrimSpace(b.String())
}
